# Generated by Django 4.0.6 on 2023-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conjugacion_future',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=40)),
                ('auxiliar', models.CharField(max_length=40)),
                ('verbo', models.CharField(max_length=40)),
                ('conjugacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Conjugacion_present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=40)),
                ('verbo', models.CharField(max_length=40)),
                ('conjugacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Conjugacion_present_continuous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=40)),
                ('auxiliar', models.CharField(max_length=40)),
                ('verbo', models.CharField(max_length=40)),
                ('conjugacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Conjugacion_preterite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=40)),
                ('verbo', models.CharField(max_length=40)),
                ('conjugacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Traduccion_de_verbos_ingles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.CharField(max_length=40)),
                ('traduccion_uno', models.CharField(max_length=40)),
                ('traduccion_dos', models.CharField(max_length=40)),
            ],
        ),
    ]
