# Generated by Django 4.0.6 on 2022-09-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conjugacion_futuro_semplice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.CharField(max_length=40)),
                ('persona', models.CharField(max_length=40)),
                ('conjugacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Conjugacion_passato_prossimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.CharField(max_length=40)),
                ('persona', models.CharField(max_length=40)),
                ('auxiliar', models.CharField(max_length=40)),
                ('conjugacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Conjugacion_presente_semplice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.CharField(max_length=40)),
                ('persona', models.CharField(max_length=40)),
                ('conjugacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Traduccion_de_verbos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.CharField(max_length=40)),
                ('traduccion_uno', models.CharField(max_length=40)),
                ('traduccion_dos', models.CharField(max_length=40)),
            ],
        ),
    ]
